import { writeFileSync } from 'fs';
import { config } from 'dotenv';

// Carica variabili da .env.local (solo in locale)
config({ path: '.env.local' });

const firebaseConfig = {
  apiKey: process.env.VITE_FIREBASE_API_KEY || '',
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.VITE_FIREBASE_PROJECT_ID || '',
  storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.VITE_FIREBASE_APP_ID || ''
};

const content = `// This file is auto-generated by scripts/generate-firebase-config.ts
// DO NOT edit manually - changes will be overwritten

export const firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};
`;

writeFileSync('src/firebase.ts', content);
console.log('✅ Firebase config generated successfully');
